version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel_api
    environment:
      DB_HOST: db
      DB_DATABASE: laravel_db
      DB_USERNAME: user
      DB_PASSWORD: user_password
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nuxt_client
    # volumes:
    #   - ./client:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
