version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: laravel_api
    environment:
      DB_HOST: db
      DB_DATABASE: laravel_db
      DB_USERNAME: user
      DB_PASSWORD: user_password
    volumes:
      - ./API:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: nuxt_client
    volumes:
      - ./Client:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
