version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ahmad@fathy
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    # ports:
    #   - "3306:3306"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel_api
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nuxt_client
    # volumes:
    #   - ./client:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
